### ISSUE TITLE
Support navigation property in compelx type

### ISSUE THREAD

**Issue by chinadragon0515** [OData/RESTier#334]
This is related https://github.com/OData/odata.net/issues/88

**Comment by chinadragon0515** [comment]
The test will include in memory data source and EF data source.

From URL path view,
~/EntitySet (has complex with Nav and NavCol, and complex Col with Nav and NavCol)
~/EntitySet/Complex
~/EntitySet/Complex? $expand=Nav,NavCol
~/EntitySet/ComplexCol? $expand=Nav,NavCol (should throw exception)
~/EntitySet/Complex/Nav
~/EntitySet/Complex/Nav/Prop
~/EntitySet/Complex/NavCol
~/EntitySet/Complex/NavCol/Prop (should throw exception)
~/EntitySet/Complex/NavCol(key)/Prop
~/EntitySet/ComplexCol/Nav (should throw exception)
~/EntitySet/ComplexCol/NavCol (should throw exception)

In $select path support test.

**Comment by chinadragon0515** [comment]
If  in memory data source is been used, need to build model with OData lib or WebAPi, and will get exception like 

[InvalidOperationException: The complex type 'Microsoft.Restier.WebApi.Test.Services.TrippinInMemory.Location' refers to the entity type 'Microsoft.Restier.WebApi.Test.Services.TrippinInMemory.Person' through the property 'Neighbors'.]
   System.Web.OData.Builder.ODataConventionModelBuilder.MapComplexType(ComplexTypeConfiguration complexType) +579
   System.Web.OData.Builder.ODataConventionModelBuilder.MapType(StructuralTypeConfiguration edmType) +151

**Comment by chinadragon0515** [comment]
For data from EF, 

From this link: 
https://msdn.microsoft.com/en-us/library/bb738472(v=vs.100).aspx

Complex type cannot contain navigation properties.

Complex type properties cannot be null. An InvalidOperationException occurs when SaveChanges is called and a null complex object is encountered. Like scalar properties of entities, scalar properties of complex objects can be null.

Complex types cannot inherit from other complex types.

**Comment by chinadragon0515** [comment]
If we define a Navigation property in complex, during model builder, this exception will be thrown,

   {"One or more validation errors were detected during model generation:\r\n\r\nMicrosoft.Restier.WebApi.Test.Services.Trippin.Models.Location: : EntityType 'Location' has no key defined. 
   Define the key for this EntityType.\r\nLocations: EntityType: EntitySet 'Locations' is based on type 'Location' that has no keys defined.\r\n"}
   at System.Data.Entity.Core.Metadata.Edm.EdmModel.Validate()
   at System.Data.Entity.DbModelBuilder.Build(DbProviderManifest providerManifest, DbProviderInfo providerInfo)
   at System.Data.Entity.DbModelBuilder.Build(DbConnection providerConnection)
   at System.Data.Entity.Internal.LazyInternalContext.CreateModel(LazyInternalContext internalContext)
   at System.Data.Entity.Internal.RetryLazy`2.GetValue(TInput input)
   at System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
   at System.Data.Entity.Internal.InternalContext.Initialize()
   at System.Data.Entity.Internal.LazyInternalContext.get_ObjectContext()
   at System.Data.Entity.DbContext.System.Data.Entity.Infrastructure.IObjectContextAdapter.get_ObjectContext()
   at Microsoft.Restier.EntityFramework.Model.ModelProducer.GetModelAsync(InvocationContext context, CancellationToken cancellationToken) 
   in d:\dev\githome\RESTier.vin\src\Microsoft.Restier.EntityFramework\Model\ModelProducer.cs:line 107
   at Microsoft.Restier.Core.Conventions.ConventionBasedApiModelBuilder.ModelBuilder.<GetModelReturnedByInnerHandlerAsync>d__17.MoveNext() in d:\dev\githome\RESTier.vin\src\Microsoft.Restier.Core\Conventions\ConventionBasedApiModelBuilder.cs:line 344

**Comment by chinadragon0515** [comment]
Move to backlog as there is no work RESTier can do now, will revisit after ODL lib support this.

**Comment by chinadragon0515** [comment]
From EF team,
We do not plan to support any of these in EF6.x. In our new EF Core code base, we do want to support #1 (support collection of primitive/enum/complex type ) and #2 (support navigation properties in complex) – but they won’t be in the v1.0  release of EF Core. We haven’t really talked about #3 (support complex inheritance), it sounds like a good idea but it’s not at the top of our backlog.

**Comment by chinadragon0515** [comment]
same as issue #137
