### ISSUE TITLE
The Any/All nesting limit of '1' has been exceeded.

### ISSUE THREAD

**Issue by jwobbe** [OData/RESTier#373]
The Any/All nesting limit of '1' has been exceeded exception is thrown when nesting 2 or more any queries.  The query causing the exception had been working until just recently when I updated to the latest version of RESTier

### Assemblies affected
Latest RESTier 0.5.0-beta  

### Reproduce steps
Run any query with nested any or all

### Expected result
I would get a valid result

### Actual result
An exception is being thrown

### Additional details
The Any/All nesting limit of '1' has been exceeded. 'MaxAnyAllExpressionDepth' can be configured on ODataQuerySettings or EnableQueryAttribute.
Original Exception StackTrace:    at System.Web.OData.Query.Validators.FilterQueryValidator.EnterLambda(ODataValidationSettings validationSettings)
   at System.Web.OData.Query.Validators.FilterQueryValidator.ValidateAnyNode(AnyNode anyNode, ODataValidationSettings settings)
   at System.Web.OData.Query.Validators.FilterQueryValidator.ValidateSingleValueNode(SingleValueNode node, ODataValidationSettings settings)
   at System.Web.OData.Query.Validators.FilterQueryValidator.ValidateQueryNode(QueryNode node, ODataValidationSettings settings)
   at System.Web.OData.Query.Validators.FilterQueryValidator.ValidateAnyNode(AnyNode anyNode, ODataValidationSettings settings)
   at System.Web.OData.Query.Validators.FilterQueryValidator.ValidateSingleValueNode(SingleValueNode node, ODataValidationSettings settings)
   at System.Web.OData.Query.Validators.FilterQueryValidator.ValidateQueryNode(QueryNode node, ODataValidationSettings settings)
   at System.Web.OData.Query.Validators.FilterQueryValidator.Validate(FilterQueryOption filterQueryOption, ODataValidationSettings settings)
   at System.Web.OData.Query.FilterQueryOption.Validate(ODataValidationSettings validationSettings)
   at System.Web.OData.Query.Validators.ODataQueryValidator.Validate(ODataQueryOptions options, ODataValidationSettings validationSettings)
   at System.Web.OData.Query.ODataQueryOptions.Validate(ODataValidationSettings validationSettings)
   at Microsoft.Restier.WebApi.RestierController.GetQuery()
   at Microsoft.Restier.WebApi.RestierController.<Get>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()

**Comment by chinadragon0515** [comment]
@jwobbe 

Now there is a default setting for some values, and they are not allowed to be customized in RESTier, we have an issue opened for this part, https://github.com/OData/RESTier/issues/359

Can I know your request URL or user scenario so we can see whether there is any workaround on this part.

In the meanwhile, we will make 359 has higher priority then you can customize and use this.

**Comment by jwobbe** [comment]
@chinadragon0515 

I have a workaround, so no need to help with that. I like the idea of [#359](https://github.com/OData/RESTier/issues/359) being implemented soon.

**Comment by chinadragon0515** [comment]
OK, I will close this issue now as we will enable the setting with issue #359. If you have any other issues, help to let me know, thanks.

**Comment by chinadragon0515** [comment]
Refer to document http://odata.github.io/RESTier/#02-09-Customize-Query-Setting on how to customize it. And note 0.5.0 is not released yet, we plan to release in coming weeks, but no guarantee.

**Comment by jwobbe** [comment]
That works.  Would it be possible to do something similar to expose ODataMessageReaderSettings?

**Comment by chinadragon0515** [comment]
@jwobbe That is planned for next RESTier release which will be based on new release of OData .Net Lib and new WebApi OData lib, both of them will adopt DI, and then we will be able to customize all the setting ODL and Web Api OData lib exposed. Can you help to open a separate issue to track this? thanks.
