### ISSUE TITLE
$apply=aggregate(Amount with sum as Total) is not working

### ISSUE THREAD

**Issue by cilerler** [OData/RESTier#449]
I wonder if we may write something like this in RESTier `...$apply=aggregate(Amount with sum as Total)` if not, can you give me any estimated time frame when it may be implemented?  Thanks in advance.

> Based on [here](http://docs.oasis-open.org/odata/odata-data-aggregation-ext/v4.0/cs01/odata-data-aggregation-ext-v4.0-cs01.html#_The_aggregate_Transformation_1) OData supports SUM through aggregate.
> Plus, @VikingsFan states in [OData issue](https://github.com/OData/WebApi/issues/70) that it supports basic aggregation and group-by

**Comment by chinadragon0515** [comment]
@VikingsFan can you help to take a look? thanks

**Comment by VikingsFan** [comment]
@cilerler do you mean it doesn't work in 0.5.0beta?

**Comment by cilerler** [comment]
@VikingsFan correct it doesn't work in 0.5.0beta?

**Comment by VikingsFan** [comment]
I tried something like .../People?$apply=aggregate(PersonId with sum as Total) with 0.5.0beta, it works,  can you share more detail information?

**Comment by cilerler** [comment]
@VikingsFan Thanks.  Once you confirmed that it is working I just tried through URL and it worked as you said. :+1: Unfortunately couldn't be able to write it in code through OData.Client.  :cry:   

Followings are the ones that I tested.  Thanks in advance.

```csharp
var total = _container.People.Aggregate(0, (result, p) => result + (int)p.Id);
```

> **The method 'Aggregate' is not supported.**
```
>   at Microsoft.OData.Client.DataServiceQueryProvider.ReturnSingleton[TElement](Expression expression)
   at Microsoft.OData.Client.DataServiceQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.Aggregate[TSource,TAccumulate](IQueryable`1 source, TAccumulate seed, Expression`1 func)
   at UserQuery.Main()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

```csharp
var total = _container.People.Sum(p.Id);
```

> **The method 'Sum' is not supported.**
```
>    at Microsoft.OData.Client.DataServiceQueryProvider.ReturnSingleton[TElement](Expression expression)
   at Microsoft.OData.Client.DataServiceQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.Sum[TSource](IQueryable`1 source, Expression`1 selector)
   at UserQuery.Main()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

```csharp
var total = _container.People.Max(p.Id);
```

> **The method 'Max' is not supported.**
```
> 
   at Microsoft.OData.Client.DataServiceQueryProvider.ReturnSingleton[TElement](Expression expression)
   at Microsoft.OData.Client.DataServiceQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.Max[TSource,TResult](IQueryable`1 source, Expression`1 selector)
   at UserQuery.Main()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by cilerler** [comment]
Based on #OData/odata.net#596 it looks like known :cry: 
Thank you for your time and attention @chinadragon0515 @VikingsFan
