### ISSUE TITLE
Make RESTier's support  Geography data type

### ISSUE THREAD

**Issue by chinadragon0515** [OData/RESTier#468]
We are working on the support for Geography data type in CollabDB and would like to ask you some questions regarding RESTier's support for Geography.

Firstly, we've been searching for some time, but still haven't found examples of Geography type in RESTier code base (unit test?). We'd appreciate it if you could point us to some examples\documentation if they're available.

Secondly, we tried implementing it and  in our implementation, we mapped data from EDM.GeographyPoint to DbGeography (.NET type) and geography (SQL type).  We did changes in ChangeSetPreparer to do the mapping between EDM.GeographyPoint to DbGeography. The POST request worked successfully; the data was stored in SQL database. However, when we issued a GET request, the data did not come through, and we received the following error:

"message": "An ODataPrimitiveValue was instantiated with a value of type 'System.Data.Entity.Spatial.DbGeography'. ODataPrimitiveValue can only wrap values which can be represented as primitive EDM types.",
"type": "Microsoft.OData.Core.ODataException",
"stacktrace": "   at Microsoft.OData.Core.ODataPrimitiveValue..ctor(Object value)\r\n  
at System.Web.OData.Formatter.Serialization.ODataPrimitiveSerializer.CreatePrimitive(Object value, IEdmPrimitiveTypeReference primitiveType, ODataSerializerContext writeContext)\r\n  
at System.Web.OData.Formatter.Serialization.ODataPrimitiveSerializer.CreateODataValue(Object graph, IEdmTypeReference expectedType, ODataSerializerContext writeContext)\r\n  
at System.Web.OData.Formatter.Serialization.ODataEdmTypeSerializer.CreateProperty(Object graph, IEdmTypeReference expectedType, String elementName, ODataSerializerContext writeContext)\r\n  
at System.Web.OData.Formatter.Serialization.ODataEntityTypeSerializer.CreateStructuralProperty(IEdmStructuralProperty structuralProperty, EntityInstanceContext entityInstanceContext)\r\n  
at System.Web.OData.Formatter.Serialization.ODataEntityTypeSerializer.CreateStructuralPropertyBag(IEnumerable`1 structuralProperties, EntityInstanceContext entityInstanceContext)\r\n  
at System.Web.OData.Formatter.Serialization.ODataEntityTypeSerializer.CreateEntry(SelectExpandNode selectExpandNode, EntityInstanceContext entityInstanceContext)\r\n  
at System.Web.OData.Formatter.Serialization.ODataEntityTypeSerializer.WriteEntry(Object graph, ODataWriter writer, ODataSerializerContext writeContext, IEdmTypeReference expectedType)\r\n  
at System.Web.OData.Formatter.Serialization.ODataFeedSerializer.WriteFeed(IEnumerable enumerable, IEdmTypeReference feedType, ODataWriter writer, ODataSerializerContext writeContext)\r\n  
at System.Web.OData.Formatter.ODataMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, HttpContent content, HttpContentHeaders contentHeaders)\r\n  
at System.Web.OData.Formatter.ODataMediaTypeFormatter.WriteToStreamAsync(Type type, Object value, Stream writeStream, HttpContent content, TransportContext transportContext, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n  
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n  
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n  
at System.Web.Http.WebHost.HttpControllerHandler.<WriteBufferedResponseContentAsync>d__1b.MoveNext()"

**Comment by rayao** [comment]
I think one way is that we add expression to query pipeline to actually create a GeopgraphyPoint from DbGeography, by wrapping any reference to DbGeography property with a "new" expression. I did this previously for DateTime to DateTimeOffset conversion, but of course it's been obsolete by the proper formatter.
So the other way maybe add conversion to formatters?

**Comment by chinadragon0515** [comment]
using conversion operator to support this, add a sample in https://github.com/OData/ODataSamples/tree/master/RESTier/SpatialSample

**Comment by rayao** [comment]
I guess this will throw for $select=FullName (or PointLocation) since EF6 expression compiler can't recognize not-mapped properties.

**Comment by rayao** [comment]
I can't repro locally though, it throws fast complaining my SQL can't support GEO types.

**Comment by chinadragon0515** [comment]
I did a test, $select will throw exception as you indicate,

message: "The specified type member 'FullName' is not supported in LINQ to Entities. Only initializers, entity members, and entity navigation properties are supported.",
type: "System.NotSupportedException",
stacktrace: "   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MemberAccessTranslator.TypedTranslate(ExpressionConverter parent, MemberExpression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TypedTranslator`1.Translate(ExpressionConverter parent, Expression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MemberInitTranslator.TypedTranslate(ExpressionConverter parent, MemberInitExpression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TypedTranslator`1.Translate(ExpressionConverter parent, Expression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MemberInitTranslator.TypedTranslate(ExpressionConverter parent, MemberInitExpression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TypedTranslator`1.Translate(ExpressionConverter parent, Expression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MemberInitTranslator.TypedTranslate(ExpressionConverter parent, MemberInitExpression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TypedTranslator`1.Translate(ExpressionConverter parent, Expression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateLambda(LambdaExpression lambda, DbExpression input)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateLambda(LambdaExpression lambda, DbExpression input, DbExpressionBinding& binding)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.OneLambdaTranslator.Translate(ExpressionConverter parent, MethodCallExpression call, DbExpression& source, DbExpressionBinding& sourceBinding, DbExpression& lambda)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.SelectTranslator.Translate(ExpressionConverter parent, MethodCallExpression call)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.SequenceMethodTranslator.Translate(ExpressionConverter parent, MethodCallExpression call, SequenceMethod sequenceMethod)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.TypedTranslate(ExpressionConverter parent, MethodCallExpression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TypedTranslator`1.Translate(ExpressionConverter parent, Expression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.Convert()
   at System.Data.Entity.Core.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClassc.<GetResultsAsync>b__a()
   at System.Data.Entity.Core.Objects.ObjectContext.<ExecuteInTransactionAsync>d__3d`1.MoveNext()

**Comment by chinadragon0515** [comment]
Also add Geography wrapper class into base code to simplify end user effort to support this.

**Comment by chinadragon0515** [comment]
geo related functions is not supported yet, refer to #470

**Comment by chinadragon0515** [comment]
The other way to support geography is ,
1. CLR class only have one property, and its Type is DbGeography
2. Model builder will make DbGeography property been shown as correct Edm type. Refer to issue for this support.
3. Write a customized serializer to convert DbGeography to correct type like GeographyPoint type.
4. Correct a customized IChangeSetInitializer, it will need to convert value in change set from GeographyPoint type to DbGeography type before calling base initializer.

As this has model builder dependency which blocks to create an end to end example now, move this one to backlog.

**Comment by chinadragon0515** [comment]
For item 4 above, 
1. In existing ChangeSetInitializer, already convert GeographyPoint and GeographyLineString, the class is also made public to allow user to add more convert.
2. The util class is create to facilitate the convert.

**Comment by chinadragon0515** [comment]
FOr item 3, refer to https://github.com/OData/ODataSamples/tree/master/RESTier/SpatialSample2, there is no plan to add EF special logic in publisher, we expect user to do something like this sample.

For the model builder, user can refer to above example using Edm model builder directly.

This issue will leave open to track model build simplify.

**Comment by robertmclaws** [comment]
Thanks for your input! We are resetting the project as we move to (finally!) ship 1.0. While we are closing this for now, we will re-address legacy feature requests at a later date. Please be sure to check out the latest nightly builds (and the upcoming 1.0 Beta 2 build) and let us know if you run into any issues. Thanks again!
