### ISSUE TITLE
RESTier throws 5** error code, if the related entity id passed in doesn’t exist

### ISSUE THREAD

**Issue by congysu** [OData/RESTier#59]
In a POST call to create an entity that has navigation property linking to another entity, if the related entity id passed in doesn’t exist, or the payload format is incorrect (without []), RESTier would throw a 5** error code.  Would expect a 400 type of error instead of 500

```json
POST http://localhost:31181/api/Northwind/Customers HTTP/1.1
Host: localhost:31181
Connection: keep-alive
Content-Length: 661
Cache-Control: no-cache
Origin: chrome-extension://fdmmgilgnpjigdojojpjoooidkmcomcm
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36
Content-Type: application/json
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.8

{
  "CustomerID": "BLON6",
  "CompanyName": "Blondesddsl père et fils",
  "ContactName": "Frédérique Citeaux",
  "ContactTitle": "Marketing Manager",
  "Address": "24, place Kléber",
  "City": "Strasbourg",
  "Region": null,
  "PostalCode": "67000",
  "CountryRegion": "France",
  "Phone": "88.60.15.31",
  "Fax": "88.60.15.32",
  "CustomerDemographics@odata.bind": "http://localhost:31181/api/Northwind/Customers('BLON6')/CustomerDemographics",
  "Orders@odata.bind": "http://localhost:31181/api/Northwind/Customers('BLON6')/Orders"
}
HTTP/1.1 500 Internal Server Error
Cache-Control: no-cache
Pragma: no-cache
Content-Type: application/json; odata.metadata=minimal
Expires: -1
Server: Microsoft-IIS/8.0
OData-Version: 4.0
X-AspNet-Version: 4.0.30319
X-SourceFiles: =?UTF-8?B?RDpccmVwb1x2c29cb2RhdGF0ZWFtXERvbWFpbkZyYW1ld29ya1xzcmNcTWljcm9zb2Z0LlJlc3RpZXIuU2FtcGxlcy5Ob3J0aHdpbmRcYXBpXE5vcnRod2luZFxDdXN0b21lcnM=?=
X-Powered-By: ASP.NET
Date: Tue, 17 Mar 2015 10:59:10 GMT
Content-Length: 2967

{
    "error": {
        "code": "",
        "message": "An error has occurred.",
        "innererror": {
  "message": "Object reference not set to an instance of an object.",
  "type": "System.NullReferenceException",
  "stacktrace": "   at Microsoft.Restier.WebApi.Extensions.CreatePropertyDictionary(Delta entity) in ...\\src\\Microsoft.Restier.WebApi\\ODataDomainController.cs:line 549
   at Microsoft.Restier.WebApi.ODataDomainController`1.<Post>d__e.MoveNext() in ...\\src\\Microsoft.Restier.WebApi\\ODataDomainController.cs:line 336
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"
        }
    }
}
```

No exception, if the request is with correct format:
```json
{
  "CustomerID": "BLON6",
  "CompanyName": "Blondesddsl père et fils",
  "ContactName": "Frédérique Citeaux",
  "ContactTitle": "Marketing Manager",
  "Address": "24, place Kléber",
  "City": "Strasbourg",
  "Region": null,
  "PostalCode": "67000",
  "CountryRegion": "France",
  "Phone": "88.60.15.31",
  "Fax": "88.60.15.32",
  "CustomerDemographics@odata.bind": ["http://localhost:31181/api/Northwind/Customers('BLON6')/CustomerDemographics"],
  "Orders@odata.bind": ["http://localhost:31181/api/Northwind/Customers('BLON6')/Orders"]
}
```

Code:
```c#
        public static IReadOnlyDictionary<string, object> CreatePropertyDictionary(this Delta entity)
        {
            Dictionary<string, object> propertyValues = new Dictionary<string, object>();
            foreach (string propertyName in entity.GetChangedPropertyNames())  //<-- null reference exception
            {
                object value;
                if (entity.TryGetPropertyValue(propertyName, out value))
                {
                    propertyValues.Add(propertyName, value);
                }
            }
            return propertyValues;
        }
```

**Comment by karataliu** [comment]
Fixed in https://github.com/OData/RESTier/commit/490391821f4a4ee876ad0c75fc7a9c5a9629c976
