### ISSUE TITLE
Latest Microsoft.AspNet.OData (7.0.0-Nightly201805221243) breaks RESTIER

### ISSUE THREAD

**Issue by cilerler** [OData/RESTier#608]
> _original issue reference https://github.com/OData/WebApi/issues/1444_

When I call `?$metadata` it throws error below
```
{
    "error": {
        "code": "",
        "message": "An error has occurred.",
        "innererror": {
            "message": "No model was specified in the ODataMessageWriterSettings; a model has to be provided in the ODataMessageWriterSettings in order to write a metadata document.",
            "type": "Microsoft.OData.ODataException",
            "stacktrace": " at Microsoft.OData.ODataMessageWriter.VerifyCanWriteMetadataDocument()
                            at Microsoft.OData.ODataMessageWriter.WriteMetadataDocument()
                            at Microsoft.AspNet.OData.Formatter.ODataOutputFormatterHelper.WriteToStream(Type type, Object value, IEdmModel model, ODataVersion version, Uri baseAddress, MediaTypeHeaderValue contentType, IWebApiUrlHelper internaUrlHelper, IWebApiRequestMessage internalRequest, IWebApiHeaders internalRequestHeaders, Func`2 getODataMessageWrapper, Func`2 getEdmTypeSerializer, Func`2 getODataPayloadSerializer, Func`1 getODataSerializerContext)
                            at Microsoft.AspNet.OData.Formatter.ODataMediaTypeFormatter.WriteToStreamAsync(Type type, Object value, Stream writeStream, HttpContent content, TransportContext transportContext, CancellationToken cancellationToken)
                            --- End of stack trace from previous location where exception was thrown ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__24.MoveNext()
                            --- End of stack trace from previous location where exception was thrown ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at System.Net.Http.HttpContent.<LoadIntoBufferAsyncCore>d__49.MoveNext()
                            --- End of stack trace from previous location where exception was thrown ---
                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at System.Web.Http.Owin.HttpMessageHandlerAdapter.<BufferResponseContentAsync>d__13.MoveNext()
                          "
        }
    }
}
```

Just change the line [here](https://github.com/xuzhg/RESTier/blob/UpdateToWebAPIOData7x/test/MyWebApplication/Global.asax.cs#L14) in sample project with code below

```csharp
    using (var httpConfiguration = GlobalConfiguration.Configuration)
    {
        //httpConfiguration.EnableDependencyInjection();

        WebApiConfig.Register(httpConfiguration);
        httpConfiguration.EnsureInitialized();
    }
```

it will work fine.

Then un-comment the commented line and you will get the error.

**Comment by robertmclaws** [comment]
I'm not experiencing this in the code currently checked into Master. Are you still experiencing it on your end? If not, I'd like to close this issue. Thanks!

**Comment by cilerler** [comment]
Unfortunately Issue is till there, simply change the line [here](https://github.com/OData/RESTier/blob/master/src/Microsoft.Restier.Samples.Northwind.AspNet/Global.asax.cs#L12) with the code below.

```csharp
    using (var httpConfiguration = GlobalConfiguration.Configuration)
    {
        //httpConfiguration.EnableDependencyInjection();

        WebApiConfig.Register(httpConfiguration);
        httpConfiguration.EnsureInitialized();
    }
```

Once you remove the comment, it throws the error

**Comment by robertmclaws** [comment]
Why would you wrap it in a Using? That disposes of the configuration when you're done. I've never seen it done that way before.

**Comment by robertmclaws** [comment]
Ok, so I looked into this, and this behavior is not unexpected. HttpConfiguration.EnableDependencyInjection is a really poorly-named function that is actually a part of OData and not a part of the DI framework. Calling this method resets the OData DI container... then Restier tries to use an empty container to do it's work.

I'll comment on the main WebAPI bug and see if I can get them to resolve the naming, and I'll update the docs to make sure to note that you're not supposed to call that line in Restier. Since this the function is actually in the OData libraries, there's nothing that can be done about it here, so I'm going to close the issue on this end.

**Comment by cilerler** [comment]
This issue hit me again. And realized that `EnableDependencyInjection` is required if you are serving controller derived from ApiController and ODataController together.

and the new error message looks like this

```json
{
  "message": "An error has occurred.",
  "exceptionMessage": "No non-OData HTTP route registered.",
  "exceptionType": "System.InvalidOperationException",
  "stackTrace": "   at Microsoft.AspNet.OData.Extensions.HttpConfigurationExtensions.GetNonODataRootContainer(HttpConfiguration configuration)\r\n   
                    at Microsoft.AspNet.OData.PerRouteContainer.GetContainer(String routeName)\r\n   
                    at Microsoft.AspNet.OData.PerRouteContainerBase.GetODataRootContainer(String routeName)\r\n   
                    at Microsoft.AspNet.OData.Extensions.HttpRequestMessageExtensions.CreateRequestScope(HttpRequestMessage request, String routeName)\r\n   
                    at Microsoft.AspNet.OData.Extensions.HttpRequestMessageExtensions.CreateRequestContainer(HttpRequestMessage request, String routeName)\r\n   
                    at Microsoft.AspNet.OData.Extensions.HttpRequestMessageExtensions.GetRequestContainer(HttpRequestMessage request)\r\n   
                    at Microsoft.AspNet.OData.Extensions.HttpRequestMessageExtensions.GetModel(HttpRequestMessage request)\r\n   
                    at Microsoft.AspNet.OData.ETagMessageHandler.<SendAsync>d__0.MoveNext()\r\n
                    --- End of stack trace from previous location where exception was thrown ---\r\n   
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   
                    at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__17`1.MoveNext()\r\n
                    --- End of stack trace from previous location where exception was thrown ---\r\n   
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   
                    at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__17`1.MoveNext()\r\n
                    --- End of stack trace from previous location where exception was thrown ---\r\n   
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   
                    at System.Web.Http.HttpServer.<SendAsync>d__24.MoveNext()"
}
```

And according to @daviburg [here](https://stackoverflow.com/a/53214606/439130)

> This is because with the new OData version the dependency injection model has changed. The suggested httpConfiguration.EnableDependencyInjection(); above allow the code to work with new OData version. 

I also found an initial description of the feature here

> ### [Enable Dependency Injection for HTTP Routes](https://odata.github.io/WebApi/13-04-DependencyInjection/)
>
> It’s also possible that you don’t want to create OData routes but just HTTP routes. The dependency injection support will NOT be enabled right after you call `MapHttpRoute`. In this case, you have to call `EnableDependencyInjection` to enable the dependency injection support for ALL HTTP routes. Please note that all the HTTP routes share the SAME root container which is of course different from the one of any OData route. That said calling `EnableDependencyInjection` has nothing to do with `MapODataServiceRoute`.
> 
> ```csharp
> configuration.MapHttpRoute(...);
> configuration.EnableDependencyInjection();
> ```

**Comment by cilerler** [comment]
[Here](https://github.com/cilerler/RESTier608) is a sample project that demonstrates the issue with the latest libraries _(including nightly RESTier)_
