### ISSUE TITLE
UnboundOperation throws an exception

### ISSUE THREAD

**Issue by Mishu** [OData/RESTier#764]
If you create an `[UnboundOperation]` (by the way `Operation` is not working as it's shown in the documentation.) and you have one or 2 strings as parameters you will get this exception:
```An exception of type 'System.InvalidCastException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'Unable to cast object of type 'Microsoft.OData.Edm.EdmPrimitiveTypeReference' to type 'Microsoft.OData.Edm.IEdmStringTypeReference'.'
   at Microsoft.OpenApi.OData.Generator.OpenApiEdmTypeSchemaGenerator.CreateSchema(ODataContext context, IEdmPrimitiveTypeReference primitiveType)
   at Microsoft.OpenApi.OData.Generator.OpenApiEdmTypeSchemaGenerator.CreateEdmTypeSchema(ODataContext context, IEdmTypeReference edmTypeReference)
   at Microsoft.OpenApi.OData.Generator.OpenApiResponseGenerator.CreateOperationResponse(ODataContext context, IEdmOperation operation)
   at Microsoft.OpenApi.OData.Generator.OpenApiResponseGenerator.CreateResponses(ODataContext context, IEdmOperation operation)
   at Microsoft.OpenApi.OData.Generator.OpenApiResponseGenerator.CreateResponses(ODataContext context, IEdmOperationImport operationImport)
   at Microsoft.OpenApi.OData.Operation.EdmOperationImportOperationHandler.SetResponses(OpenApiOperation operation)
   at Microsoft.OpenApi.OData.Operation.OperationHandler.CreateOperation(ODataContext context, ODataPath path)
   at Microsoft.OpenApi.OData.PathItem.PathItemHandler.AddOperation(OpenApiPathItem item, OperationType operationType)
   at Microsoft.OpenApi.OData.PathItem.OperationImportPathItemHandler.SetOperations(OpenApiPathItem item)
   at Microsoft.OpenApi.OData.PathItem.PathItemHandler.CreatePathItem(ODataContext context, ODataPath path)
   at Microsoft.OpenApi.OData.Generator.OpenApiPathItemGenerator.CreatePathItems(ODataContext context)
   at Microsoft.OpenApi.OData.Generator.OpenApiPathsGenerator.CreatePaths(ODataContext context)
   at Microsoft.OpenApi.OData.Generator.OpenApiDocumentGenerator.CreateDocument(ODataContext context)
   at Microsoft.OpenApi.OData.EdmModelOpenApiExtensions.ConvertToOpenApi(IEdmModel model, OpenApiConvertSettings settings)
   at Microsoft.OpenApi.OData.EdmModelOpenApiExtensions.ConvertToOpenApi(IEdmModel model)
   at Brainiac.Host.RestierSwaggerProvider.GetSwagger(String documentName, String host, String basePath) in ...\Program.cs:line 422
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__4.MoveNext()
```
This only happens for the Swagger generation. The actual queries works fine.

### Assemblies affected
<PackageReference Include="Microsoft.Restier.AspNetCore" Version="1.1.1" />
<PackageReference Include="Microsoft.Restier.AspNetCore.Swagger" Version="1.1.1" />
<PackageReference Include="Microsoft.Restier.Core" Version="1.1.1" />
<PackageReference Include="Microsoft.Restier.EntityFrameworkCore" Version="1.1.1" />
<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
<PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="6.6.2" />
<PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="6.6.2" />

### Reproduce steps
As said in this comment: [https://github.com/OData/RESTier/issues/720#issuecomment-1826782823](Issue #720)

### Expected result
Correctly generate the OpenApi json and Swagger UI.

### Actual result
An exception is thrown when accessing the Swagger endpoint.
 

### Additional details
If I make them `BoundOperation` the error goes away but they are completely ignored in Swagger.

Any thoughts?
Thank you!

**Comment by Mishu** [comment]
You need to add string parameters to the operations.

**Comment by cilerler** [comment]
You can not.  You have to define it as `ComplexType`.
Here is a workaround.

```csharp
[Microsoft.Restier.AspNetCore.Model.UnboundOperation(OperationType = Microsoft.Restier.AspNetCore.Model.OperationType.Action)]
public IQueryable<EmailAddress> GetEmailsToValidate(StringRequest input)
{
	// ...
	return query.AsQueryable();
}

public class CustomModelExtender : IModelBuilder
{
    public IModelBuilder InnerHandler { get; set; }

    public IEdmModel GetModel(ModelContext context)
    {
	    IEdmModel model = InnerHandler.GetModel(context);
    
	    var modelBuilder = new ODataConventionModelBuilder();
	    modelBuilder.ComplexType<StringResponse>();
    
	    return modelBuilder.GetEdmModel();
    }
}

public class StringRequest
{
	public string Value { get; set; }
}

public static IHostApplicationBuilder AddRestierInternal(this IHostApplicationBuilder builder)
{
          builder.Services.AddRestier(b =>
		          {
			          // This delegate is executed after OData is added to the container.
			          b.AddRestierApi<ApiController>(routeServices =>
			          {
			              // ...
                                      routeServices.AddChainedService<IModelBuilder, CustomModelExtender>();
                                      // ...
			          }
		          });
}
```

**Comment by Mishu** [comment]
Hello,
Thank you for your answer!
It's working now.
One quick question, do you happen to have an example of how to call the function? The url for it?

This is how I'm calling it: 
```
https://localhost:8762/odata/GetEmailsToValidate(input =@ input)?@ input ={"Value":"test"}
```

And when I do, I get this exception:

```
{
    "error": {
        "code": "",
        "message": "Value cannot be null. (Parameter 's')",
        "details": [],
        "innererror": {
            "message": "Value cannot be null. (Parameter 's')",
            "type": "System.ArgumentNullException",
            "stacktrace": "   at void ArgumentNullException.Throw(string paramName)\r\n   at byte[] System.Text.Encoding.GetBytes(string s)\r\n   at object Microsoft.AspNet.OData.Formatter.ODataModelBinderConverter.ConvertResourceOrResourceSet(object oDataValue, IEdmTypeReference edmTypeReference, ODataDeserializerContext readContext)\r\n   at object Microsoft.AspNet.OData.Formatter.ODataModelBinderConverter.Convert(object graph, IEdmTypeReference edmTypeReference, Type clrType, string parameterName, ODataDeserializerContext readContext, IServiceProvider requestContainer)\r\n   at object Microsoft.Restier.AspNetCore.Formatter.DeserializationHelpers.ConvertValue(object odataValue, string parameterName, Type expectedReturnType, IEdmTypeReference propertyType, IEdmModel model, HttpRequest request, IServiceProvider serviceProvider)\r\n   at async Task<IQueryable> Microsoft.Restier.AspNetCore.Operation.RestierOperationExecutor.ExecuteOperationAsync(OperationContext context, CancellationToken cancellationToken)\r\n   at async Task<IActionResult> Microsoft.Restier.AspNetCore.RestierController.Get(CancellationToken cancellationToken)\r\n   at async ValueTask<IActionResult> Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)\r\n   at async Task Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()+Awaited(?)\r\n   at async Task Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()+Awaited(?)\r\n   at void Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Task Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)\r\n   at Task Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n   at async Task Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextExceptionFilterAsync()+Awaited(?)"
        }
    }
}
```

Thanks!

**Comment by cilerler** [comment]
```http
###
# @name GetEmailsToValidate
POST {{baseUrl}}/odata/GetEmailsToValidate HTTP/1.1
Content-Type: application/json
Cache-Control: no-cache

{
  "stringRequest": {
    "@odata.type": "#MyCompany.MyModels.Dto.Request.StringRequest",  // <== correct this checking it from the $metadata
    "Value": "me@test.local"
  }
}
```

**Comment by Mishu** [comment]
Thanks, thats for an Action, for a function with GET?

**Comment by cilerler** [comment]
A simple GET request is unlikely to work because it requires `@odata.type` and an explicit declaration of the **object** name. On the client side, if you are using **ODataClient**, it handles these details automatically and uses a POST request based on the cases I've observed.

**Comment by Mishu** [comment]
Oh, ok, thanks!
I'll try with ODataClient from the Angular App. I've tried POST, I got Method not allowed. I'm adding the `@odata.type`, not really sure on the "explicit declaration of the object" though.

I'll try that and come back with results.
Thank you so much for the assistance so far!

**Comment by cilerler** [comment]
1. Update the part below.
> [!WARNING]
> ```json
> {
>   "input": { <== update this
>     "@odata.type": "#MyCompany.MyModels.Dto.Request.StringRequest",  // <== correct this checking it from the `/odata/$metadata`
>     "Value": "me@test.local"
>   }
> }
> ```
2. Make sure your HTTP request is working first and then try it from the application.
